autoperry/autoperry/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include('webapp.urls')),
    path("django-admin/", admin.site.urls, name="django-admin"),
]

autoperry/webapp/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path(r'favicon.ico', RedirectView.as_view(url=staticfiles_storage.url("webapp/favicon.ico"))),
    path(r'privacy/', TemplateView.as_view(template_name="webapp/privacy.html"), name='privacy'),
    path(r'help/about/', TemplateView.as_view(template_name="webapp/about.html"), name='about'),
    path(r'help/organisers/', TemplateView.as_view(template_name="webapp/organisers.html"), name='guidelines-organisers'),
    path(r'help/helpers/', TemplateView.as_view(template_name="webapp/helpers.html"), name='guidelines-helpers'),
    path(r'help/shortcuts/', TemplateView.as_view(template_name="webapp/shortcuts.html"), name='shortcuts'),
    path(r'help/calendars/', TemplateView.as_view(template_name="webapp/calendars.html"), name='calendars'),
    path(r"accounts/password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(r"accounts/", include("django.contrib.auth.urls")),
    path(r"account/", views.account, name="account"),
    path(r"account/create/", views.account_create, name="account-create"),
    path(r"account/confirm/<uidb64>/<token>/", views.account_confirm, name="account-confirm"),
    path(r"account/resend/", views.account_resend, name="account-resend"),
    path(r"account/edit/", views.account_edit, name="account-edit"),
    path(r"account/cancel/", views.account_cancel, name="account-cancel"),
    path(r"events/", views.events, name="events"),
    path(r"event/create/", views.event_create, name="event-create"),
    path(r"event/<int:event_id>/", views.event_details, name="event-details"),
    path(r"event/<int:event_id>/cancel/", views.event_cancel, name="event-cancel"),
    path(r"event/<int:event_id>/edit/", views.event_edit, name="event-edit"),
    path(r"event/<int:event_id>/clone/", views.event_clone, name="event-clone"),
    path(r"event/<int:event_id>/volunteer/", views.volunteer, name="volunteer"),
    path(r"event/<int:event_id>/unvolunteer/", views.unvolunteer, name="unvolunteer"),
    path(r"event/<int:event_id>/decline/<int:helper_id>/", views.decline, name="decline"),
    path(r"events-csv/", views.events_csv, name="events-csv"),
    path(r"admin/send-emails/", views.send_emails, name="send-emails"),
    path(r"admin/account-list/", views.account_list, name="account-list"),
    path(r"admin/account-list-csv/", views.account_list_csv, name="account-list-csv"),
    path(r"admin/account-approve-list/", views.account_approve_list, name="account-approve-list"),
    path(r"admin/account-approve/<int:user_id>/", views.account_approve, name="account-approve"),
    path(r"admin/account/delete/<str:where_from>/<int:user_id>/", views.account_delete, name="account-delete"),
    path(r"stats/", views.stats_screen, name="stats"),
    path(r"ical/future/<str:uuid>/", views.ical_future, name="ical-future"),
    path(r"ical/<str:uuid>/", views.ical, name="ical"),
]

autoperry/webapp/models.py
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.utils.dateformat import format
from django.template.defaultfilters import force_escape, urlize
from django.utils.safestring import mark_safe
from django.urls import reverse

import datetime

from custom_user.models import User


# Create your models here.

class Event(models.Model):
    start = models.DateTimeField(blank=False)
    end = models.DateTimeField(blank=False, null=True)
    location = models.CharField(max_length=128, blank=False)
    helpers_required = models.IntegerField(blank=False, verbose_name='helpers needed')
    owner = models.ForeignKey(User, models.DO_NOTHING, related_name='events_owned')
    helpers = models.ManyToManyField(User, through="Volunteer", related_name='events_volunteered')
    created = models.DateTimeField(auto_now_add=True)
    cancelled = models.DateTimeField(null=True, blank=True)
    contact_address = models.EmailField(blank=True, null=True, help_text="Contact email address for the event, defaults to owner's address")
    notes = models.CharField(max_length=200, blank=True, null=True, help_text="Purpose of the event, helper skills required, etc.")
    owner_reminded = models.DateTimeField(null=True, blank=True)
    alerts = models.BooleanField(default=False)

    # Also
    #
    # volunteer_set (filter volunteer) to access the individual volunteering records

    def has_current_helper(self, user):
        """
        tests if user is a current (so not withdrawn, not declined)
        helpers for an event
        """
        return bool(self.volunteer_set.current().filter(person=user))


    @property
    def current_helpers(self):
        """
        Return a QuerySet representing all current (so not withdrawn,
        not declined) helpers for this event
        """
        return (get_user_model().objects.
            filter(
                volunteer__event=self,
                volunteer__withdrawn=None,
                volunteer__declined=None
            )
       )

    @property
    def n_helpers_available(self):
        """
        Return the number of current helpers
        """
        return len(self.current_helpers)


    @property
    def contact(self):
        """
        Contact address for this event
        """
        return self.contact_address if self.contact_address else self.owner.email


    @property
    def contact_info(self):
        """
        Contact information for this event
        """

        result = urlize(self.contact)
        if self.owner.phone_number:
            result += f', {force_escape(self.owner.phone_number)}'
        return mark_safe(result)

    @property
    def contact_info_text(self):
        """
        Contact information for this event as text
        """

        result = self.contact
        if self.owner.phone_number:
            result += f', {self.owner.phone_number}'
        return result


    @property
    @admin.display(boolean=True)
    def past(self):
        """
        Is this event in the past?
        """
        if self.start:
            return self.start < timezone.now()
        return False

    @property
    @admin.display(boolean=True)
    def is_cancelled(self):
        """
        Has this event been cancelled?
        """
        return self.cancelled != None


    @property
    @admin.display(boolean=True)
    def helpers_needed(self):
        """
        Does this event still need helpers?
        """
        if self.helpers_required:
            return self.helpers_required > len(self.volunteer_set.current()) and not self.cancelled and not self.past
        return True

    @property
    @admin.display(ordering='start')
    def when(self):
        """
        Date of the event with start and end times
        """
        start = self.start
        end = self.end
        # Only include AM on start if event spans midday
        include_am = ''
        if start.hour <12 and end.hour >= 12:
            include_am = ' a'
        return (format(start, f"l, j F Y, g:i{include_am}") +
                ' to ' +
                format(end, "g:i a"))

    @property
    @admin.display(ordering='start')
    def short_when(self):
        """
        Short format date of the event with start and end times
        """
        start = self.start
        end = self.end
        # Only include year if it's not the current one
        include_year = ''
        if start.year !=  datetime.date.today().year:
            include_year = ' Y'
        # Only include AM on start if event spans midday
        include_am = ''
        if start.hour <12 and end.hour >= 12:
            include_am = ' a'
        return (format(start, f"D, j M{include_year}, g:i{include_am}") +
                '-' +
                format(end, f"g:i{include_am}"))

    def get_absolute_url(self):
        return reverse('event-details', args=[self.pk])

    def __str__(self):
    	return f'{self.location} - {self.short_when} [#{self.pk}]'

    class Meta:
        ordering = ["start"]


class VolunteerManager(models.Manager):

    """
    Add a custom method to only return volunteer objects that haven't
    been withdrawn or declined
    """

    def current(self):
        return self.filter(withdrawn=None, declined=None)


class Volunteer(models.Model):
    event = models.ForeignKey(Event, models.DO_NOTHING)
    person = models.ForeignKey(User, models.DO_NOTHING)
    created = models.DateTimeField(auto_now_add=True)
    withdrawn = models.DateTimeField(null=True, blank=True)
    declined = models.DateTimeField(null=True, blank=True)

    objects = VolunteerManager()

    @property
    @admin.display(boolean=True)
    def current(self):
        return self.withdrawn == None and self.declined == None

    def __str__(self):
        return f'"{self.person}"/"{self.event}" [#{self.pk}]'

    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=['event'], name='event_index')]

autoperry/webapp/forms.py
# webapp/forms.py

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from django.utils import timezone
from django.core.exceptions import ValidationError

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

from datetime import date, time, datetime, timedelta

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = list(UserCreationForm.Meta.fields) + ["email", "first_name", "last_name", "tower", "phone_number", "send_notifications", "send_other"]
        fields.remove("username")
        model = get_user_model()


def today_or_tomorrow():
    """
    Return tomorrows date if it's past 19:30, else todays date
    """
    now = datetime.now()
    if now.time() > time(hour=19, minute=30):
        return (now + timedelta(days=1)).date()
    return now.date()

class EventForm(forms.Form):
    date = forms.DateField(help_text='Event date', initial=today_or_tomorrow, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    start_time = forms.TimeField(help_text='Event start time', initial="19:30", widget=forms.widgets.DateInput(format="%H:%M", attrs={'type': 'time', 'step': 300}))
    end_time = forms.TimeField(help_text='Event finish time', initial="21:00", widget=forms.widgets.DateInput(format="%H:%M", attrs={'type': 'time', 'step': 300}))
    location = forms.CharField(max_length=60, help_text='Where the event takes place')
    helpers_required = forms.IntegerField(min_value=1, label='Helpers wanted', help_text='Number of helpers wanted', initial=1)
    contact_address = forms.CharField(max_length=60, required=False, help_text="Email address for the event (yours if blank)")
    notes = forms.CharField(max_length=200, required=False, help_text="Purpose of the event, helper skills required, etc. (optional, max 200 chars.)")
    alerts = forms.BooleanField(required=False, label="Send emails when helpers change")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('date', css_class='form-group col-md-4 mb-0'),
                Column('start_time', css_class='form-group col-md-4 mb-0'),
                Column('end_time', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('location', css_class='form-group col-md-8 mb-0'),
                Column('helpers_required', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            'contact_address',
            'notes',
            'alerts'
        )

    def clean(self):
        cleaned_data = super().clean()
        date = cleaned_data.get("date")
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")

        if date and start_time and end_time:

            if start_time >= end_time:
                raise ValidationError("End time must be later than start time!")

            start = datetime.combine(date, start_time)
            if start < timezone.now():
                raise ValidationError("Event start is in the past. Events must start in the future!")

    class Media:
        css = {
            'all': ('webapp/jquery-ui.min.css',)
        }
        js = ('webapp/jquery.min.js', 'webapp/jquery-ui.min.js')

class UserEditForm(forms.Form):
    email = forms.EmailField(help_text="You will need to re-confirm your email address if you change this")
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    tower = forms.CharField(max_length=50, help_text="Where do you normally ring")
    phone_number = forms.CharField(required=False, help_text="Optional, useful in case of last-minute cancellations or changes of plan")
    send_notifications = forms.BooleanField(required=False, label="Send email alerts and reminders about your events")
    send_other = forms.BooleanField(required=False, label="Send other emails")

class EmailForm(forms.Form):
    helpers = forms.BooleanField(required=False, initial=True, label="Include helpers?")
    organisers = forms.BooleanField(required=False, initial=True, label="Include organisers?")
    rest = forms.BooleanField(required=False, initial=True, label="Include others?")
    subject = forms.CharField(required=True)
    message = forms.CharField(required=True, widget=forms.Textarea)

autoperry/webapp/templates/webapp/account-approve-list.html
<!--webapp/templates/index.html-->

{% extends 'webapp/authn.html' %}

{% block content %}

<h2 class="text-center">Users awaiting approval</h2>

<div class="row justify-content-center">
    <div class="col-auto">

{% if users %}

      <table class="table table-responsive">

       <thead>
        <tr>
        <td class="fw-bold">Name</td>
        <td class="fw-bold">Tower</td>
        <td class="fw-bold">Address</td>
        <td class="fw-bold">Phone</td>
        <td class="fw-bold">Waiting</td>
        <td class="fw-bold"></td>
      </tr>
    </thead>

    <tbody class="table-group-divider">


   {% for u in users %}
      <tr class="text-start">

        <td>{{ u.first_name }} <b>{{ u.last_name }}</b></td>

        <td>{{ u.tower }}</td>

        <td>{{ u.email|urlize }}</td>

        <td>{{ u.phone_number }}</td>

        <td>{{ u.date_joined|timesince }}</td>

        <td><a href="{% url 'account-approve' user_id=u.pk %}" class="btn btn-outline-primary btn-sm">approve</a></td>

        <td><a href="{% url 'account-delete' where_from='approve' user_id=u.pk %}" class="btn btn-secondary btn-danger btn-sm">delete</a></td>

      </tr>

   {% endfor %}

      </table>

{% else %}

<div class="alert alert-warning mt-3" role="alert">
There are no users awaiting approval
</div>

{% endif %}

   </div>

</div>

{% endblock %}

autoperry/webapp/templates/webapp/account-approve.html
<!--webapp/templates/index.html-->

{% extends 'webapp/authn.html' %}

{% block content %}

<h2>Approve an account</h2>

<dl>

    <dt>Name:</dt>
    <dd>{{ candidate.first_name }} {{ candidate.last_name }}</dd>

    <dt>Tower</dt>
    <dd>{{ candidate.tower|default:'[none]' }}</dd>

    <dt>Email</dt>
    <dd>{{ candidate.email|urlize }}</dd>

    <dt>Phone number</dt>
    <dd>{{ candidate.phone_number }}</dd>

</dl>

<p>Please confirm that this person should have access to AutoPerry</p>

<form method="post">
    {% csrf_token %}
    <input class="btn btn-primary{% if errors %} disabled{% endif %}" type="submit" name="confirm" value="Approve">
</form>

{% endblock %}

autoperry/webapp/templates/webapp/account-delete.html
{% extends 'webapp/authn.html' %}

{% block content %}

<h2>Delete account</h2>

<dl>

    <dt>Name:</dt>
    <dd>{{ candidate.first_name }} {{ candidate.last_name }}</dd>

    <dt>Tower</dt>
    <dd>{{ candidate.tower|default:'[none]' }}</dd>

    <dt>Email</dt>
    <dd>{{ candidate.email|urlize }}</dd>

    <dt>Phone number</dt>
    <dd>{{ candidate.phone_number }}</dd>

</dl>

<p>Are you sure you want to delete this account? This action can not be undone.</p>

<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" name="confirm" value="Yes, delete this account">
</form>

{% endblock %}

autoperry/webapp/templates/webapp/account-edit.html
<!--webapp/templates/index.html-->

{% extends 'webapp/authn.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h2>Edit your account</h2>

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Save">
</form>

<p><a href="{% url 'privacy' %}">How we use the information you provide</a></p>

{% endblock %}

autoperry/webapp/templates/webapp/account-list.html
<!--webapp/templates/index.html-->

{% extends 'webapp/authn.html' %}

{% load humanize %}

{% block content %}

<h2 class="text-center">Users</h2>

<form>

  <input type="hidden" name="f" value="1">

  <div class="row align-items-center justify-content-center">

	<div class="col-auto">
      <div class="form-check">
	    <input class="form-check-input" id="pending" name="pending" onchange="this.form.submit()" type="checkbox" value="yes" {% if flags.pending %}checked{% endif %}>
	    <label class="form-check-label" for="past">Include pending?</label>
      </div>
    </div>

    <div class="col-auto">
      <div class="form-check">
	    <input class="form-check-input" id="current" name="current" onchange="this.form.submit()" type="checkbox" value="yes"{% if flags.current %}checked{% endif %}>
	    <label class="form-check-label" for="cancelled">Include current?</label>
      </div>
    </div>

    <div class="col-auto">
      <div class="form-check">
        <input class="form-check-input" id="suspended" name="suspended" onchange="this.form.submit()" type="checkbox" value="yes"{% if flags.suspended %}checked{% endif %}>
        <label class="form-check-label" for="suspended">Include suspended?</label>
      </div>
    </div>

    <div class="col-auto">
      <div class="form-check">
        <input class="form-check-input" id="cancelled" name="cancelled" onchange="this.form.submit()" type="checkbox" value="yes"{% if flags.cancelled %}checked{% endif %}>
        <label class="form-check-label" for="canceleld">Include cancelled?</label>
      </div>
    </div>

  </div>

</form>

<div class="row align-items-center justify-content-center mt-2 mb-2">
  <div class="col-auto">A = not approved</div>
  <div class="col-auto">E = email not validated</div>
  <div class="col-auto">S = suspended</div>
  <div class="col-auto">C = cancelled</div>
  <div class="col-auto">H = helper</div>
  <div class="col-auto">O = organiser</div>
</div>

<div class="row justify-content-center">
    <div class="col-auto">

      {% if users %}

      <table class="table table-responsive table-sm">

        <thead>
        <tr>
        <td class="fw-bold">Name<br>Tower</td>
        <td class="fw-bold">Email<br>Phone</td>
        <td class="fw-bold">Created<br>Last Login</td>
        <td colspan="4" class="fw-bold">Flags</td>
        <td colspan="2" class="fw-bold">Counts</td>
        <td class="fw-bold">&nbsp;</td>
        <td class="fw-bold">&nbsp;</td>
      </tr>
    </thead>

    <tbody class="table-group-divider">

   {% for user in users %}



      <tr class="text-start">

        <td>
          {{ user.first_name }} <b>{{ user.last_name }}</b><br>
          {{ user.tower }}
        </td>

        <td>
          {{ user.email|urlize }}
          {% if user.send_notifications and user.send_other %}
          {% elif user.send_notifications %}
          (alerts only)
          {% elif user.send_other %}
          (other only)
          {% else %}
          (no emails)
          {% endif %}
          <br>
          {{ user.phone_number|truncatechars:30 }}
        </td>

        <td>
          {{ user.date_joined|date:"j M Y"}}<br>
          {{ user.last_login|date:"j M Y"|default:"never"}}
        </td>

        <td>{% if user.approved == None %}A{% endif %}</td>
        <td>{% if user.email_validated == None %}E{% endif %}</td>
        <td>{% if user.suspended != None %}S{% endif %}</td>
        <td>{% if user.cancelled != None %}C{% endif %}</td>

        <td>{% if user.num_helped %}H:{{ user.num_helped }} ({{ user.rank | ordinal }}){% endif %}</td>
        <td>{% if user.num_owned %}O:{{ user.num_owned }}{% endif %}</td>

        <td>
          <form method="post">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{ user.pk }}">
            <div class="form-check">
               <input class="form-check-input" id="suspended" name="suspended" onchange="this.form.submit()" type="checkbox" value="yes" {% if user.suspended %}checked{% endif %}>
               <label class="form-check-label" for="email_blocked">Suspended?</label>
            </div>
            <div class="form-check">
               <input class="form-check-input" id="email_blocked" name="email_blocked" onchange="this.form.submit()" type="checkbox" value="yes" {% if user.email_blocked %}checked{% endif %}>
               <label class="form-check-label" for="email_blocked">Email&nbsp;blocked?</label>
            </div>
          </form>
        </td>

        <td>
        {% if not user.approved %}
          <a href="{% url 'account-delete' where_from='account' user_id=user.pk %}" class="btn btn-danger btn-sm">delete</a>
        {% else %}
          &nbsp;
        {% endif %}
      </td>

      </tr>

   {% endfor %}

 </tbody>

      </table>

<nav>
    <ul class="pagination justify-content-center">
      {% for page in page_range %}
        {% if page == 'X' %}
        <li class="page-item disabled"><span class="page-link">&hellip;</span></li>
        {% else %}
          <li class="page-item{% if page == users.number %} active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% endif %}
        {% endfor %}
    </ul>
</nav>

<p><a href="{% url 'account-list-csv' %}" class="btn btn-outline-secondary btn-sm">Download all users as CSV</a></p>


      {% else %}

      <div class="alert alert-warning mt-3" role="alert">
      No users match the filters selected
      </div>

      {% endif %}

   </div>

</div>

{% endblock %}

autoperry/webapp/templates/webapp/base.html
<!--webapp/templates/base.html-->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AutoPerry</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'webapp/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'webapp/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'webapp/autoperry.css' %}">
    <link rel="apple-touch-icon" href="{% static 'webapp/apple-touch-icon.png' %}">
    <style>

</style>

</head>

<body>

  <div class="container-fluid">

{% include 'webapp/navigation.html' %}

{% if messages %}
    {% for message in messages %}
    <div class="alert{% if message.tags %} {{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
{% endif %}

{% if user.is_authenticated and user.email_blocked %}
  <div class="alert alert-danger d-flex"  role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </svg>
    <div>
      Emails to this account's address (<i>{{ user.email }}</i>) have been suspended, probably because
      the address doesn't seem to be working. If you think this address should work you can try
      <a class="alert-link" href="{% url 'account-resend' %}">re-confirming it</a>. Otherwise
      you can change your address from <a class="alert-link" href="{% url 'account-edit' %}">your account
      edit page</a>.
    </div>
  </div>
{% endif %}

{% block content %}{% endblock %}

  <footer class="d-flex flex-wrap justify-content-between align-items-top py-3 my-4 border-top">
    <div class="col-md-6 d-flex align-items-center">
      <span class="mb-3 mb-md-0 text-muted">AutoPerry is provided by and for the
      <a href="https://cambridgeringing.info/" class="link-secondary">Cambridge District</a> of the
      <a href="https://www.elyda.org.uk/" class="link-secondary">Ely Diocesan Association of Church Bell Ringers</a></span>
    </div>

    <div class="col-md-4 justify-content-end d-flex text-muted">
      <a href="mailto:autoperry@cambridgeringing.info" class="link-secondary">autoperry@cambridgeringing.info</a>
    </div>
  </footer>

  </div>

  <script src="{% static 'webapp/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

autoperry/webapp/templates/webapp/event-create.html
<!--webapp/templates/index.html-->


{% extends 'webapp/authn.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="col-md-8 mx-auto">

<h2>Create an event</h2>

<p>Please make sure you have read the <a href="{% url 'guidelines-organisers' %}">guidelines
for event organisers</a> before creating an event.</p>

{{ form.media }}
<form method="post" action="{% url 'event-create' %}">
{% crispy form %}
<input class="btn btn-primary" type="submit" value="Create event">
</form>

<script  type="text/javascript">
$( "#id_location" ).autocomplete({
  source: [
  {% for location in locations %}"{{location|escapejs}}",{% endfor %}
  ]
});
</script>

</div>

{% endblock %}

autoperry/webapp/templates/webapp/helpers.html
<!--webapp/templates/index.html-->

{% extends 'webapp/authn.html' %}

{% block content %}

<div class="running">

<h2>Guidelines for helpers</h2>

<ul>

	<li>Unless you have opted out of alerts and reminders, you should receive an
    e-mail reminder on Sundays for the events you have volunteered for in the
    following week.</li>

    <li>You should also receive an automatic alert if an event you have
    agreed to help with is cancelled or if its timing is altered. Organisers
    are also encouraged to alert you by phone for events that were
    imminent. If you haven't provided a phone number, or if you don't allow
    alert and reminder emails, then you should check the web site before
    setting off.</li>

    <li>Please turn up on time (or at least warn the organiser if you won’t be
    able to).</li>

    <li>Remember, your job is to fit in and do whatever is needed to support
    the home band.  If you are not given the opportunity to circle the tower,
    or turn in the tenor, so be it.</li>

    <li>If you have useful suggestions or insights to offer, please do so,
    tactfully.</li>

    <li>Even if you don’t like the way the practice is being run, please go
    along with it, and certainly don’t try and take over.  You don’t have to
    volunteer there again!  If you have any serious concerns, please contact
    the District's Practice Night Support Officer at
    {{ 'pnso@cambridgeringing.info'|urlize }}.</li>

    <li>You must only use personal information that you find here
    (names, email addresses, phone numbers, etc.) to manage bell ringing
    support through events managed on this site and for nothing else without
    the individual's permission.</li>
  </ul>

</div>

{% endblock %}

autoperry/webapp/templates/webapp/volunteer-clash-error-fragment.html
<p>You have already volunteered to help with {% if clashes|length == 1 %}an event{% else %}events{% endif %} at the same time as this one:</p>
<ul class="m-0">
    {% for clash in clashes %}
    <li><a href="{% url 'event-details' event_id=clash.pk %}" class="alert-link">{{ clash.location }} - {{ clash.start|date:"g:i" }} to {{ clash.end|date:"g:i a" }}</a></li>
    {% endfor %}
</ul>